#!/usr/bin/python3
def raise_exception():
    a = "84"
    b = 24
    result = a + b
    return result
